live_config_reload = true

import = ["~/.config/alacritty/alacritty-theme/themes/kanagawa_dragon.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "full"
dynamic_padding = false
blur = true
opacity = 0.88
option_as_alt = "Both"

[window.padding]
x = 16
y = 16

[font]
size = 18.0

[font.bold]
family = "RobotoMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "RobotoMono Nerd Font Mono"
style = "Regular"

[font.italic]
family = "RobotoMono Nerd Font Mono"
style = "Regular"

[font.normal]
family = "RobotoMono Nerd Font Mono"
style = "Regular"

[mouse]
hide_when_typing = true

[debug]
render_timer = false
