
[env]
TERM = "xterm-256color"

[terminal]
shell = { program = 'C:\WINDOWS\system32\wsl.exe', args = ["--cd", "~"] }

[window]
decorations = "buttonless"
dynamic_padding = false
blur = true
opacity = 0.99

[window.padding]
x = 8
y = 8

[font]
size = 12.0

[font.bold]
family = "RobotoMono Nerd Font Mono"
style = "Heavy"

[font.bold_italic]
family = "RobotoMono Nerd Font Mono"
style = "Heavy Italic"

[font.italic]
family = "RobotoMono Nerd Font Mono"
style = "Medium Italic"

[font.normal]
family = "RobotoMono Nerd Font Mono"
style = "Medium"

[mouse]
hide_when_typing = true

[debug]
render_timer = false

[general]
live_config_reload = true

import = [
  "~\\AppData\\Roaming\\alacritty\\alacritty-theme\\themes\\rose-pine-moon.toml"
]

[[keyboard.bindings]]
key = "Space"
mods = "Control"
chars = "\u0000"

[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"
